### ISSUE TITLE
Define "length of page"

### ISSUE THREAD

**Issue by baileyheit** [ulfaslak/caobd_f19#4]
I am a bit confused by what you mean by the "length of the page of each character"

Using some code, I found found that the number of pages is very large and also equal to the pageid. Is this what you are looking for? I am also giving the page "size" which I assume is in bytes. Or are we looking for number of pages on each wiki site? 

If you can, a more clear definition would be helpful.

Tak!

**Comment by baileyheit** [comment]
Follow up question. are the ambiguous characters the ones that are both heroes and villains? Or is there a separate list?

**Comment by Avanderheyde** [comment]
I just took the length of the markup as a proxy for the length of each page. Don't know if that is correct though. 

Yes, the ambiguous characters are both heroes and villains.

**Comment by ulfaslak** [comment]
@Avanderheyde Exactly. So if you have the markup of some page stored in a variable `markup`, then the length of the given page is `len(markup)`. Thanks for asking.

On your second question: yes. Both categorized as heroes and villains.
