### ISSUE TITLE
ex 2.2.5 scatterplots

### ISSUE THREAD

**Issue by sidswear** [ulfaslak/caobd_f19#8]
For numbers 3 and 4, I didn't get any meaningful looking results just using pca.fit_transform(X). 
Is this the right transformation to apply? What should the scatterplots look like?

**Comment by ulfaslak** [comment]
Here's what my figure looks like:

<img width="414" alt="ex 2 2 5 4" src="https://user-images.githubusercontent.com/6390218/65446772-5b6cca00-de35-11e9-9a27-2d81fa5db452.png">
